// src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styles: [
  ]
})
export class LoginComponent implements OnInit {
  message: string = 'Connectez-vous';
  name: string;
  password: string;
  auth: AuthService;

  constructor(private authService: AuthService, private router :Router) { }

  ngOnInit(): void {
    this.auth = this.authService;
  }

  setMessage() {
    if(this.auth.isLoggedIn) {
      this.message = 'Vous êtes connecté';
    } else {
      this.message = 'Identifiant ou mots de passe incorrect'
    }
  }

  login() {
    this.message = 'Authentification en cours';
    this.auth.login(this.name, this.password).subscribe((isLoggedIn: boolean) => {
      this.setMessage();
      if(isLoggedIn) {
        this.router.navigate(['pokemons']);
      } else {  
        this.password = '';
        this.router.navigate(['login']);
      }
    })
  }

  logout() {
    this.auth.logout();
    this.message = 'Vous êtes déconnecté';
  }
}

<div class="row" style="margin-top: 32px;">
    <div class="col s12 m6 offset-m3">
        <div class="card hoverable">
            <div class="card-content center">
                <span class="card-title" style="font-weight: bold; cursor: default;">Page de connexion</span>
                <p style="cursor: default"><em>{{message}}</em></p>
                <form #loginForm="ngForm">
                    <div>
                        <label for="name">Name</label>
                        <input type="text" id="name" [(ngModel)]="name" name="name" required>
                    </div>
                    <div>
                        <label for="password">Password</label>
                        <input type="password" id="password" [(ngModel)]="password" name="password" required>
                    </div>
                </form>
            </div>
            <div class="card-action center">
                <a (click)="login()" class="waves-effect waves-light btn"  *ngIf="!auth.isLoggedIn">Se connecter</a>
            </div>
        </div>
    </div>
</div>

// client/src/pages/login.tsx
import { ChangeEvent, FunctionComponent, useState } from "react";
import { useHistory } from "react-router-dom";
import AuthenticationService from "../services/authentication-service";

type Field = {
  value: any;
  error?: string;
  isValid?: boolean;
};

type Form = {
  username: Field;
  password: Field;
};

const Login: FunctionComponent = () => {
  const history = useHistory();

  const [form, setForm] = useState<Form>({
    username: { value: "" },
    password: { value: "" },
  });

  const [message, setMessage] = useState<string>(
    "Vous êtes déconnecté (Identifiant : EdouardY, Mot de passe : Pokemon)"
  );

  const handleInputChange = (e: ChangeEvent<HTMLInputElement>): void => {
    const fieldName: string = e.target.name;
    const fieldValue: string = e.target.value;
    const newField = { [fieldName]: { value: fieldValue } };

    setForm({ ...form, ...newField });
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    setMessage("👉 Tentative de connexion en cours ...");
    AuthenticationService.login(form.username.value, form.password.value).then(
      (isAuthenticated) => {
        if (!isAuthenticated) {
          setMessage("🔐 Identifiant ou mot de passe incorrect.");
          return;
        }

        history.push("/pokemons");
      }
    );
  };

  return (
    <form onSubmit={(e) => handleSubmit(e)}>
      <div className="row">
        <div className="col s12 m8 offset-m2">
          <div className="card hoverable">
            <div className="card-stacked">
              <div className="card-content">
                {/* Form message */}
                {message && (
                  <div className="form-group">
                    <div className="card-panel grey lighten-5">{message}</div>
                  </div>
                )}
                {/* Field username */}
                <div className="form-group">
                  <label htmlFor="username">Identifiant</label>
                  <input
                    id="username"
                    type="text"
                    name="username"
                    className="form-control"
                    value={form.username.value}
                    onChange={(e) => handleInputChange(e)}
                  ></input>
                </div>
                {/* Field password */}
                <div className="form-group">
                  <label htmlFor="password">Mot de passe</label>
                  <input
                    id="password"
                    type="password"
                    name="password"
                    className="form-control"
                    value={form.password.value}
                    onChange={(e) => handleInputChange(e)}
                  ></input>
                </div>
              </div>
              <div className="card-action center">
                {/* Submit button */}
                <button type="submit" className="btn">
                  Valider
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
  );
};

export default Login;
